# Generated by Django 3.2.9 on 2021-11-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='recipient',
            field=models.TextField(blank=True, verbose_name='Кому поставлена задача'),
        ),
    ]
